- name: Project Service Playbook
  block:
    - name: Set systemd service unit variables
      set_fact:
        systemd_unit_name: "{{ project_name }}-{{ branch_name }}.service"
        systemd_unit_path: "/etc/systemd/system/{{ systemd_unit_name }}.service"

    - name: Create Docker Service 
      include_tasks: docker/create_docker_service.yml

    - name: Enable and start service
      ansible.builtin.systemd:
        name: "{{ systemd_unit_name }}"
        state: started
        enabled: yes
      become: yes
      ignore_errors: yes