---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: python:3.10-slim-bullseye
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        ansible_user: root
verifier:
  name: ansible
